'use client';
import {useEffect,useRef} from 'react';

type Point={venue_id:string;name:string;region:string;latitude:number;longitude:number;avg_rating:number|null;rating_count:number};
const colours:Record<string,string>={bangalore:'#b83f35',chennai:'#31845f',delhi:'#cf852e',hyderabad:'#4e78b2'};

export default function VenueMap({points,regions,region}:{points:Point[];regions:Record<string,string>;region:string}){
 const element=useRef<HTMLDivElement>(null);
 useEffect(()=>{let map:any;let cancelled=false;(async()=>{if(!element.current)return;const module=await import('leaflet');const L=module.default;if(cancelled||!element.current)return;map=L.map(element.current,{preferCanvas:true,scrollWheelZoom:true}).setView([20.59,78.96],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const layer=L.layerGroup().addTo(map);const renderer=L.canvas({padding:.25});const bounds:any[]=[];for(const point of points){if(!Number.isFinite(point.latitude)||!Number.isFinite(point.longitude))continue;const latlng:[number,number]=[point.latitude,point.longitude];bounds.push(latlng);const marker=L.circleMarker(latlng,{radius:5,weight:1,color:'#fff',fillColor:colours[point.region]||'#704fa3',fillOpacity:.82,renderer}).addTo(layer);const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=point.name;const detail=document.createElement('p');detail.textContent=`${regions[point.region]||point.region} · ${point.avg_rating==null?'Unrated':point.avg_rating.toFixed(2)+' stars'} · ${point.rating_count.toLocaleString('en-IN')} rating records`;const link=document.createElement('a');link.href='/venues/'+point.venue_id;link.textContent='View historical record →';popup.appendChild(title);popup.appendChild(detail);popup.appendChild(link);marker.bindPopup(popup)}if(bounds.length)map.fitBounds(bounds,{padding:[28,28],maxZoom:12})})();return()=>{cancelled=true;if(map)map.remove()}},[points,regions]);
 return <section className="panel map-panel"><div className="panel-head"><div><h2>Interactive historical venue map</h2><p>{points.length.toLocaleString('en-IN')} coordinate records · historical snapshot, not current availability</p></div><label className="map-filter">Source region<select value={region} onChange={e=>window.location.assign('/map'+(e.target.value?'?region='+encodeURIComponent(e.target.value):''))}><option value="">All regions</option>{Object.entries(regions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div ref={element} className="venue-map" aria-label="Interactive map of historical venue coordinates"/><div className="map-legend">{Object.entries(regions).map(([value,label])=><span key={value}><i style={{background:colours[value]||'#704fa3'}}/>{label}</span>)}</div><p className="footnote">Map tiles © OpenStreetMap contributors. Coordinates and source-region assignments come from the historical third-party dataset and may be outdated or imprecise.</p></section>;
}
